## This program computes inverse of a matrix and stores the result
## in the cache, if the same matrix is re-run the program 
## returns results stored in the cache.

## makeCacheMatrix is initialized to null, if a matrix inverse
## has been generated by the cachesolve() the value is stored in
## makeCacheMatrix

makeCacheMatrix <- function(x = matrix()){
      m <- NULL
      set <- function(y) {
            x <<- y
            m <<- NULL
      }
      get <- function() x
      setmatrixinv <- function(solve) m <<- solve
      getmatrixinv <- function() m
      list(set = set, get = get,
           setmatrixinv = setmatrixinv,
           getmatrixinv = getmatrixinv)
}

## cacheSolve checks if a matrix has been solved and the solution
## available in cache, if solution is available in cache then 
## the solution is returned from cache. ifelse the matrix is
## solved and the solution is returned to cache for storing.


cacheSolve <- function(x, ...){
      m <- x$getmatrixinv()
      if(!is.null(m)) {
            message("getting cached data")
            return(m)
      }
      data <- x
      m <- solve(data)
      x$setmatrixinv(m)
      m  ## Return a matrix that is the inverse of 'x'
}
